### ISSUE TITLE
PCB sharp Corners in layout

### ISSUE THREAD

**Issue by Uspizig** [martinberlin/H-C6-ulp#2]
<img width="830" alt="image" src="https://github.com/user-attachments/assets/811c6f55-11f2-46c8-80c7-e26ccf5a7a95">
Please avoid such sharp edges in PCB. This will result in underfill.

<img width="824" alt="image" src="https://github.com/user-attachments/assets/1d11b24b-c635-4314-9009-4f44dfe1caaa">

**Comment by martinberlin** [comment]
Spider legs now look nicer
![C6 legs](https://github.com/user-attachments/assets/3a0f1611-6447-4e06-9acf-ba4939537e76)
If you like the PCB project and it works will send you one as a present
